version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.1.4-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_net

volumes:
  rabbitmq_data: # Persist RabbitMQ data even if the container is removed - clean it up: docker volume rm rabbitmq_data

networks:
  rabbitmq_net: # Custom network for communication (can be shared with other services)